#
# application.yml — главный конфигурационный файл Spring Boot.

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.

server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost/bank-rest-database
    username: postgres
    password: roottoor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
  liquibase:
    change-log: classpath:/db/migration/changelog.yml

token:
  signing:
    key: KJIS8H5HG73MGJHD8R94JG0W0JPSEO48HBDY4F330IGN4